[workspace]
resolver = "2"
members = [
  "domain",
  "server",
  "site",
]
default-members = [ "server" ]

[workspace.package]
version = "0.15.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
domain = { path = "./domain" }
serde = { version = "1.0.217", features = ["derive"] }

