[package]
name = "domain"
version.workspace = true
edition = "2021"

[lib]
name = "domain"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsql = { workspace = true }
serde = { workspace = true }